name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create GitHub Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify app bundle exists
        run: |
          if [ ! -d "Save Image.app" ]; then
            echo "Save Image.app not found in repo at tag ${GITHUB_REF_NAME}" >&2
            exit 1
          fi

      - name: Zip app bundle
        run: |
          rm -f "Save Image.app.zip"
          ditto -c -k --sequesterRsrc --keepParent "Save Image.app" "Save Image.app.zip"
          ls -lh "Save Image.app.zip"

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          name: Save Image ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            Save Image.app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

