name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify app bundle exists
        run: |
          if [ ! -d "Save Image.app" ]; then
            echo "Save Image.app not found in repo at tag ${GITHUB_REF_NAME}" >&2
            exit 1
          fi

      - name: Zip app bundle
        run: |
          rm -f "Save Image.app.zip"
          ditto -c -k --sequesterRsrc --keepParent "Save Image.app" "Save Image.app.zip"
          ls -lh "Save Image.app.zip"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Save Image ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Save Clipboard-Image for macOS.
            - Prebuilt app bundled from this repo at tag ${{ github.ref_name }}
            - Usage: Right-click Open on first launch (Gatekeeper), or remove quarantine: xattr -dr com.apple.quarantine "~/Applications/Save Image.app"

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Save Image.app.zip
          asset_name: Save Image.app.zip
          asset_content_type: application/zip
